* Emacs configuration

This is my emacs configuration, this time in Org mode.  The previous
working version of it was [[https://github.com/pepegar/emacs.d/tree/d6c5ef558fc4a28f7b107a4edb5c1383886a23d6][this commit]].

The idea behind using org mode for this is that I can get rid of all
these cheatsheets I've flying around my system (and also physical
desk) and have both the emacs-lisp code, the notes, and the
cheatsheets all here.


** Initial configuration
*** Some personal information

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Pepe García"
      user-mail-address "jl.garhdez@gmail.com")
#+END_SRC

*** load ~/.emacs.d/lisp

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
#+END_SRC

*** Help emacs find my executables

#+BEGIN_SRC emacs-lisp
(setq exec-path (append exec-path '("/usr/local/bin")))
(setq exec-path (append exec-path '("/Users/pepe/.local/bin")))
(setq exec-path (append exec-path '("/Users/pepe/.nix-profile/bin")))
(setq exec-path (append exec-path '("/nix/var/nix/profiles/default/bin/")))
#+END_SRC

*** plumbing

    To tell emacs that all saves should go to the ~/.backups~ folder.

#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist `(("." . "~/.backups")))
#+END_SRC

    Save the custom variables to ~\~/.emacs.d/custom.el~

#+BEGIN_SRC emacs-lisp
(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)
#+END_SRC

*** ~use-package~

   I manage all the packages for my emacs configuration through the
   fantastic [[https://github.com/jwiegley/use-package][use-package]]. Here's how to get it:

#+BEGIN_SRC emacs-lisp
(require 'package)

(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(require 'bind-key)
#+END_SRC

*** Appearance

    Select the font size, family...

#+BEGIN_SRC emacs-lisp
(set-face-attribute
 'default nil :family "PragmataPro"
 :height 150)

(use-package all-the-icons
  :ensure t)

(use-package all-the-icons-dired
  :ensure t
  :init (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+END_SRC

*** maintaining selected theme between sessions

    I think I got all this from @anler, but am not sure :)

#+BEGIN_SRC emacs-lisp
(defun my-load-saved-theme ()
  (interactive)
  (when (file-exists-p my-saved-theme-filename)
    (let ((theme (intern (with-temp-buffer
                           (insert-file-contents my-saved-theme-filename)
                           (buffer-string)))))
      (unless (eq theme 'default)
        (load-theme theme :no-confirm)))))

(add-hook 'after-init-hook #'my-load-saved-theme)

(defvar my-load-theme-hook
  nil
  "Hooks to run after loading a theme.")

(defvar my-saved-theme-filename "~/.emacs.d/.emacs-theme")

(advice-add 'load-theme :after #'my-save-theme)
(advice-add 'disable-theme :after #'my-save-default-theme)
(advice-add 'load-theme :after #'my-run-theme-hooks)

(defun my-run-theme-hooks (theme &optional no-confirm no-enable)
  (run-hooks 'my-load-theme-hook))

(defun my-save-default-theme (disabled-theme)
  (my-save-theme 'default))

(defun my-save-theme (theme &optional no-confirm no-enable)
  (with-temp-buffer
    (insert (symbol-name theme))
    (when (file-writable-p my-saved-theme-filename)
      (write-region (point-min)
                    (point-max)
                    my-saved-theme-filename))))
#+END_SRC

** Tools

*** company
    Company is an autocompletion framework for emacs!

#+BEGIN_SRC emacs-lisp
(use-package company
  :ensure t
  :bind (("M-n" . company-complete)))
#+END_SRC
*** paredit

#+BEGIN_SRC emacs-lisp
(use-package paredit
  :ensure t
  :config
  (add-hook 'emacs-lisp-mode-hook #'paredit-mode)
  (add-hook 'lisp-interaction-mode-hook #'paredit-mode)
  (add-hook 'ielm-mode-hook #'paredit-mode)
  (add-hook 'lisp-mode-hook #'paredit-mode)
  (add-hook 'eval-expression-minibuffer-setup-hook #'paredit-mode))
#+END_SRC

*** Gnus

    Gnus is for email within emacs.  Its configuration is in ~\~/.emacs.d/gnus.org~

*** Erc

    Erc is an IRC client for emacs.

#+BEGIN_SRC emacs-lisp
(use-package erc
  :ensure t
  :config
    (setq erc-modules '(autojoin notifications)))
#+END_SRC

*** Magit

    Magit is a better way to use git, from within emacs, of course.

#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t)
#+END_SRC

    There are several tricks I like to do with Magit.

**** commit & spinoff branch

     Normally, when I work on a small patch for a project I don't
     directly start creating the feature branch, but first create the
     commit/commits that solve the issue and then create the branch &
     pull request.

     I do this by fixing and creating the commits normally (on top of
     ~master~), and then within the magit screen, I just hit ~b s~,
     making a spinoff of master, with the last commits.  This is so
     convenient :)

**** managing/creating pull requests

     For creating pull requests, I use the ~magit-gh-pulls~ package,
     that connects to the github API via HTTP and allows me to create,
     list, and see the Pull Requests for the repo.

     Normally I need to edit the ~.git/config~ file and add the remote
     github repo:

#+BEGIN_SRC
[magit]
        gh-pulls-repo = pepegar/$repo
#+END_SRC

     After that's set, I can just ~# g~ to refresh the latest pull
     requests, ~# o~ on a pr of the list to open in firefox, or ~# c~
     to create a new PR from the existing changes.

*** Projectile

#+BEGIN_SRC emacs-lisp
(use-package projectile
  :ensure t
  :config
  (projectile-global-mode)
  (setq projectile-mode-line
        '(:eval (format " [%s]" (projectile-project-name))))
  (setq projectile-remember-window-configs t)
  (setq projectile-completion-system 'ivy))
#+END_SRC
*** Diminish

    You don't always want the minor modes you're using to appear on
    the modeline, that's what ~diminish~ is for.

#+BEGIN_SRC emacs-lisp
(use-package diminish
  :ensure t
  :pin melpa-stable)
#+END_SRC

*** Flycheck

    Flycheck is a spellchecker.  Truth be told, I don't use it very
    much... but yeah, here it is!

#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :pin melpa-stable)
#+END_SRC

*** Ivy, counsel, swiper

    I'm mostly a helm user, but want to give ivy a try now.  Ivy comes
    out of the box with ~counsel~ and ~swiper~.

**** Search the word under the cursor

     Open swiper-isearch with ~C-s~, and then put copy the word under
     the cursor to the minibuffer with ~M-n~.

     For extending the search to the next word, use ~M-j~.

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :ensure t
  :diminish ivy-mode
  :bind (("C-x C-b" . ivy-switch-buffer))
  :config
      (setq ivy-use-virtual-buffers t
            ivy-count-format "%d/%d "
            ivy-re-builders-alist '((swiper . ivy--regex-plus)
                                    (t      . ivy--regex-fuzzy)))

  (use-package flx
    :ensure t)

  (use-package counsel
    :ensure t
    :bind (("C-c a g" . counsel-projectile-ag)
           ("M-x"     . counsel-M-x)
           ("C-x C-f" . counsel-find-file)
           ("C-c p h" . counsel-projectile)
           ([f9]      . counsel-load-theme)))

  (use-package counsel-projectile
    :ensure t)

  (use-package swiper
    :ensure t
    :bind (("C-s" . swiper)
           ("C-;" . swiper-avy))))
#+END_SRC

*** ace-window

    ace-window is a better ~other-window~.

#+BEGIN_SRC emacs-lisp
(use-package ace-window
  :ensure t
  :bind (("M-o" . ace-window)))
#+END_SRC

*** Hydra

    Hydra allows me to create menus of keybindings.  I have several
    ones, for accessing my dotfiles, spelllchecking, going to my org
    files...

#+BEGIN_SRC emacs-lisp
(use-package hydra
  :ensure t
  :bind (("C-x t" . toggle/body)
	 ("C-x j" . gotoline/body)
	 ("C-x c" . orghydra/body)
	 ("C-x p" . dotfiles/body))
  :config

  (defhydra toggle (:color blue)
    "toggle"
    ("a" abbrev-mode "abbrev")
    ("s" flyspell-mode "flyspell")
    ("f" flycheck-mode "flycheck")
    ("d" toggle-debug-on-error "debug")
    ("c" fci-mode "fCi")
    ("t" toggle-truncate-lines "truncate")
    ("w" whitespace-mode "whitespace")
    ("q" nil "cancel"))

  (defhydra orghydra (:color blue)
    "org"
    ("i" org-clock-in "clock in")
    ("o" org-clock-out "clock out")
    ("n" (find-file "~/org/notes.org") "notes.org")
    ("I" (find-file "~/org/i.org") "i.org")
    ("q" nil "cancel"))

  (defhydra dotfiles (:color black)
    "dotfiles"
    ("c" (find-file "~/.emacs.d/config.org") "config.org")
    ("z" (find-file "~/.zshrc") "zshrc")
    ("g" (find-file "~/.emacs.d/gnus.org") "gnus")
    ("q" nil "cancel"))

  (defhydra gotoline
    ( :pre (linum-mode 1)
	   :post (linum-mode -1))
    "goto"
    ("t" (lambda () (interactive)(move-to-window-line-top-bottom 0)) "top")
    ("b" (lambda () (interactive)(move-to-window-line-top-bottom -1)) "bottom")
    ("m" (lambda () (interactive)(move-to-window-line-top-bottom)) "middle")
    ("e" (lambda () (interactive)(end-of-buffer)) "end")
    ("c" recenter-top-bottom "recenter")
    ("n" next-line "down")
    ("p" (lambda () (interactive) (forward-line -1))  "up")
    ("g" goto-line "goto-line")))
#+END_SRC

*** Restclient

    Restclient is an awesome tool that allows you to describe HTTP
    request in plain text and execute them.  From [fn:1]their readme:

    | keybinding | action                                                                                         |
    |------------+------------------------------------------------------------------------------------------------|
    | ~C-c C-c~  | runs the query under the cursor, tries to pretty-print the response (if possible)              |
    | ~C-c C-r~  | same, but doesn't do anything with the response, just shows the buffer                         |
    | ~C-c C-v~  | same as C-c C-c, but doesn't switch focus to other window                                      |
    | ~C-c C-p~  | jump to the previous query                                                                     |
    | ~C-c C-n~  | jump to the next query                                                                         |
    | ~C-c C-.~  | mark the query under the cursor                                                                |
    | ~C-c C-u~  | copy query under the cursor as a curl command                                                  |
    | ~C-c C-g~  | start a helm session with sources for variables and requests (if helm is available, of course) |
    | ~C-c n n~  | narrow to regi                                                                                 |

#+BEGIN_SRC emacs-lisp
(use-package restclient
  :ensure t
  :mode (("\\.http\\'" . restclient-mode)))
#+END_SRC

*** Org mode

    I try to write down everything in org mode, and to keep it
    updated.  This is my current configuration.

#+BEGIN_SRC emacs-lisp
(use-package org
  :ensure t
  :bind (("C-c a a" . org-agenda)
	 ("C-c c" . counsel-org-capture))
  :config

  (use-package org-bullets
    :ensure t
    :commands (org-bullets-mode)
    :init (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))

  (org-babel-do-load-languages
   'org-babel-load-languages
   '((dot . t)
     (mscgen . t)
     (python . t)))
  (setq org-agenda-files '("~/org/")
	org-default-notes-file (concat org-directory "/notes.org")
	org-capture-templates '(("a" "Appointment" entry (file  "~/org/appointments.org" "Appointments") "* TODO %?\n:PROPERTIES:\n\n:END:\nDEADLINE: %^T \n %i\n\n")
				("n" "Note" entry (file+headline "~/org/notes.org" "Notes") "* Note %?\n%T")
				("l" "Link" entry (file+headline "~/org/links.org" "Links") "* %? %^L %^g \n%T" :prepend t)
                                ("j" "Journal Entry" entry (file+datetree "~/org/journal.org") "* %?" :empty-lines 1)
				("P" "Paper" entry (file+headline "~/org/papers.org" "Papers") "* %? %^L %^g \n%T" :prepend t)
				("t" "To Do Item" entry (file+headline "~/org/i.org" "Work") "* TODO %?\n%T" :prepend t)
				("p" "Personal To Do Item" entry (file+headline "~/org/i.org" "Personal") "* TODO %?\n%T" :prepend t))
	org-src-fontify-natively t))
#+END_SRC

*** Multiple cursors

#+BEGIN_SRC emacs-lisp
(use-package multiple-cursors
  :ensure t
  :bind (("C-* l" . mc/edit-lines)
	 ("C->" . mc/mark-next-like-this)
	 ("C-<" . mc/mark-previous-like-this)
         ("C-* C-*" . mc/mark-all-like-this)
         ("C-c C-* C-*" . mc/mark-more-like-this)
         ("C-* i" . mc/insert-numbers)
         ("C-* s" . mc/sort-regions)
         ("C-* r" . mc/reverse-regions)
         ("M-<mouse-1>" . mc/add-cursor-on-click))
  :init
  (global-unset-key (kbd "M-<down-mouse-1>"))
  :config
  (require 'mc-extras))

(use-package mc-extras
  :ensure t
  :commands (mc/compare-chars mc/compare-chars-backward mc/compare-chars-forward
            mc/cua-rectangle-to-multiple-cursors
            mc/remove-current-cursor mc/remove-duplicated-cursors)
  :config
  (progn
    (bind-keys :map mc/keymap
         ("C-. C-d" . mc/remove-current-cursor)
         ("C-. d" . mc/remove-duplicated-cursors)
         ("C-. =" . mc/compare-chars))
    (eval-after-load 'cua-base
'(bind-key "C-. C-," 'mc/cua-rectangle-to-multiple-cursors cua--rectangle-keymap))))
#+END_SRC

*** Expand region

    Expand region is an useful little tool.  With it I can select a
    higher region each time I hit ~C-@~.  For example, imagine we have
    the following function call in lisp (and that the caret is in the
    ~^~ position):

#+BEGIN_SRC
(hello (dolly))
         ^
#+END_SRC

    If I hit ~C-@~ once, I'll get this selected:

#+BEGIN_SRC
(hello (dolly))
        ^---^
#+END_SRC

    If I hit it once again, I'll get:

#+BEGIN_SRC
(hello (dolly))
       ^-----^
#+END_SRC

    And if I hit it again, I'll get:

#+BEGIN_SRC
(hello (dolly))
 ^-----------^
#+END_SRC

    Finally, if I hit it 4 times, the whole sexp will be selected:

#+BEGIN_SRC
(hello (dolly))
^-------------^
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package expand-region
  :ensure t
  :bind ("C-@" . er/expand-region))
#+END_SRC

*** Avy

    Avy allows me to jump to different parts of the current buffer.
    There are some useful pictures of how it works in [[https://github.com/abo-abo/avy][the repo]].

#+BEGIN_SRC emacs-lisp
(use-package avy
  :ensure t)
#+END_SRC

*** Golden ratio

    Golden ratio makes splits looks better :)

#+BEGIN_SRC emacs-lisp
(use-package golden-ratio
  :ensure t
  :diminish golden-ratio-mode
  :config (golden-ratio-mode))
#+END_SRC

** Themes

   I switch between a big number of themes, sometimes several times a
   day, depending on my mood.  The ones I stick with as of now, are
   the following:

#+BEGIN_SRC emacs-lisp
(use-package doom-themes :pin melpa-stable :ensure t :defer t)
(use-package spacemacs-theme :pin melpa :ensure t :defer t)
(use-package idea-darkula-theme :ensure t :defer t)
(use-package punpun-theme :ensure t :defer t)
(use-package white-theme :ensure t :defer t)
(use-package arjen-grey-theme :ensure t :defer t)
(use-package atom-one-dark-theme :ensure t :defer t)
(use-package birds-of-paradise-plus-theme :ensure t :defer t)
(use-package bliss-theme :ensure t :defer t)
(use-package cyberpunk-theme :ensure t :defer t)
(use-package espresso-theme :ensure t :defer t)
(use-package github-theme :ensure t :defer t)
(use-package heroku-theme :ensure t :defer t)
(use-package idea-darkula-theme :ensure t :defer t)
(use-package plan9-theme :ensure t :defer t)
(use-package soothe-theme :ensure t :defer t)
(use-package subatomic-theme :ensure t :defer t)
(use-package sublime-themes :ensure t :defer t)
(use-package white-theme :ensure t :defer t)
(use-package madhat2r-theme :ensure t :defer t)
(use-package kosmos-theme :ensure t :defer t)
(use-package nord-theme :ensure t :defer t)
#+END_SRC

** Programming languages

   At the time of writing this, I mostly write scala, but I've used a
   number of languages previously:

*** Scala

    The following cheatsheet is copied from [[https://github.com/ensime/ensime.github.io/blob/master/editors/emacs/cheat_sheet.md][Ensime's cheatsheet for
    emacs]], for having a local copy, basically :D

**** Source

| Shortcut                   | Description                                                                        |
|----------------------------+------------------------------------------------------------------------------------|
| ~C-c C-v f~                | Format the current source file                                                     |
| ~C-c C-v t~ or hover mouse | Show the type of the symbol under the cursor                                       |
| ~C-c C-v T~                | Show the fully qualified type of the symbol under the cursor                       |
| ~C-u C-c C-v t~            | (universal argument adds to the kill ring)                                         |
| ~C-c C-v e~ or hover mouse | Show compile warnings under the cursor ; show implicit conversions when applicable |

**** Presentation Compiler

| Shortcut    | Description                                          |
|-------------+------------------------------------------------------|
| ~C-c C-c c~ | Re-typecheck the current file                        |
| ~C-c C-c r~ | Restart the presentation compiler for all open files |

**** Refactoring

| Shortcut    | Description                             |
|-------------+-----------------------------------------|
| ~C-c C-r a~ | Add type to the symbol under the cursor |
| ~C-c C-r o~ | Organize imports in the current file    |
| ~C-c C-r t~ | Import the type under the cursor        |
| ~C-c C-r r~ | Rename the symbol under the cursor      |
| ~C-c C-r l~ | Extract the region into a local value   |
| ~C-c C-r m~ | Extract the region into a method        |
| ~C-c C-r i~ | Inline the local value under the cursor |

**** Navigation

| Shortcut                      | Description                                                                                                               |
|-------------------------------+---------------------------------------------------------------------------------------------------------------------------|
| ~M-.~ or ~Control+Left-Click~ | Jump to the definition of the symbol under the cursor                                                                     |
| ~C-u M-.~                     | Jump to the definition of the type of the symbol under the cursor                                                         |
| ~C-c C-v r~                   | Find usage of symbol at point                                                                                             |
| ~C-c C-v h~                   | Find implementations of type at point                                                                                     |
| ~M-,~                         | Pop back to the previously visited position                                                                               |
| ~C-c C-v .~                   | Select the surrounding syntactic context. Subsequent taps of '.' and ',' will grow and shrink the selection, respectively |
| ~C-c C-v v~                   | Search globally for methods or types                                                                                      |

**** Documentation

| Shortcut    | Description                                             |
|-------------+---------------------------------------------------------|
| ~C-c C-v d~ | Browse the documentation of the symbol under the cursor |

**** sbt

Much of this is a wrapper over [~sbt-mode~](https://github.com/hvesalai/sbt-mode), so don't forget that you also have commands provided as-is by that package.


| Shortcut                   | Description                                          |
|----------------------------+------------------------------------------------------|
| ~C-c C-b s~ or ~C-c C-v s~ | Start a sbt process, or switch to an existing one    |
| ~C-c C-b S~                | Switch to buffer containing the stack trace parser   |
| ~C-c C-b c~                | Compile                                              |
| ~C-c C-b C~                | Compile just this file                               |
| ~C-u C-c C-b C~            | Compile just this file and print its AST             |
| ~C-c C-b n~                | Clean                                                |
| ~C-c C-b p~                | Package                                              |
| ~C-c C-b r~                | Run                                                  |
| ~C-c C-b T~                | Run all tests                                        |
| ~C-c C-b t~                | Run the current module/suite tests                   |
| ~C-c C-b q~                | Run "quick" tests (tests impacted by recent changes) |
| ~C-c C-b o~                | Run only the current test                            |

**** Debugger

| Shortcut    | Description                                      |
|-------------+--------------------------------------------------|
| ~C-c C-d d~ | Start the debugger                               |
| ~C-c C-d b~ | Set a breakpoint at the current line             |
| ~C-c C-d u~ | Remove the breakpoint at the current line        |
| ~C-c C-d a~ | Remove all breakpoints                           |
| ~C-c C-d r~ | Start debugging the current program              |
| ~C-c C-d s~ | Step into method invocations                     |
| ~C-c C-d o~ | Step out of method invocations                   |
| ~C-c C-d n~ | Step to the next line                            |
| ~C-c C-d c~ | Continue the program execution                   |
| ~C-c C-d q~ | Stop debugging the current program               |
| ~C-c C-d t~ | Show the current backtrace                       |
| ~C-c C-d i~ | Inspect the value of the symbol under the cursor |

**** REPL

| Shortcut      | Description                               |
|---------------+-------------------------------------------|
| ~C-c C-v z~   | Start the Scala REPL or switch to it      |
| ~C-c C-v C-r~ | Send the region to the REPL               |
| ~C-c C-v b~   | Evaluate the current buffer in the REPL   |
| ~C-c C-v l~   | Prompt for a file and load it in the REPL |

**** Miscellaneous

| Shortcut              | Description                                       |
|-----------------------+---------------------------------------------------|
| ~C-c C-b S~           | Create a "stacktrace" buffer or switch to it      |
| ~M-x ensime-shutdown~ | Shut down ENSIME                                  |
| ~M-x ensime-reload~   | Reload the .ensime file and recompile the project |




#+BEGIN_SRC emacs-lisp
(use-package ensime
  :ensure t
  :pin melpa-stable
  :config
  (defhydra ensime-hydra (:color blue)
    "useful ensime things"
    ("c" ensime-sbt-do-compile "compile")
    ("s" ensime-sbt "sbt")
    ("t" ensime-sbt-do-test "test")))

(use-package scala-mode
  :ensure t
  :interpreter ("scala" . scala-mode)
  :config
  (use-package sbt-mode
    :ensure t
    :config (setq sbt:program-name "/usr/local/bin/sbtx")))
#+END_SRC

*** others

#+BEGIN_SRC emacs-lisp
(use-package lsp-mode
  :ensure t)

(use-package haskell-mode
  :ensure t
  :config
  (use-package intero
    :ensure t
    :config
     (add-hook 'haskell-mode-hook 'intero-mode)))


(use-package idris-mode :ensure t)
(use-package nix-mode :ensure t)
(use-package groovy-mode :ensure t)
(use-package yaml-mode :ensure t)
(use-package json-mode :ensure t)

(use-package markdown-mode
  :ensure t
  :mode "\\.md\\'"
  :config

  (use-package markdown-toc
    :ensure t))
#+END_SRC

** Some more configuration for when all packages has been loaded

#+BEGIN_SRC emacs-lisp
(require 'diminish)
(require 'bind-key)

(electric-pair-mode 1)
#+END_SRC

** Weird characters I write

   In a day to day basis, I only use the ~λ~ there, but who knows? Now
   I can write most of those letters :)

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-g a") "α") ; alpha
(global-set-key (kbd "M-g b") "β") ; beta
(global-set-key (kbd "M-g g") "γ") ; gamma
(global-set-key (kbd "M-g d") "δ") ; delta
(global-set-key (kbd "M-g e") "ε") ; epsilon
(global-set-key (kbd "M-g z") "ζ") ; zeta
(global-set-key (kbd "M-g h") "η") ; eta
(global-set-key (kbd "M-g q") "θ") ; theta
(global-set-key (kbd "M-g i") "ι") ; iota
(global-set-key (kbd "M-g k") "κ") ; kappa
(global-set-key (kbd "M-g l") "λ") ; lambda
(global-set-key (kbd "M-g m") "μ") ; mu
(global-set-key (kbd "M-g n") "ν") ; nu
(global-set-key (kbd "M-g x") "ξ") ; xi
(global-set-key (kbd "M-g o") "ο") ; omicron
(global-set-key (kbd "M-g p") "π") ; pi
(global-set-key (kbd "M-g r") "ρ") ; rho
(global-set-key (kbd "M-g s") "σ") ; psi
(global-set-key (kbd "M-g t") "τ") ; tau
(global-set-key (kbd "M-g u") "υ") ; upsilon
(global-set-key (kbd "M-g f") "ϕ") ; phi
(global-set-key (kbd "M-g j") "φ") ; phi
(global-set-key (kbd "M-g c") "χ") ; xi
(global-set-key (kbd "M-g y") "ψ") ; psi
(global-set-key (kbd "M-g w") "ω") ; omega
(global-set-key (kbd "M-g A") "Α") ; ALPHA
(global-set-key (kbd "M-g B") "Β") ; BETA
(global-set-key (kbd "M-g G") "Γ") ; GAMMA
(global-set-key (kbd "M-g D") "Δ") ; DELTA
(global-set-key (kbd "M-g E") "Ε") ; EPSILON
(global-set-key (kbd "M-g Z") "Ζ") ; ZETA
(global-set-key (kbd "M-g H") "Η") ; ETA
(global-set-key (kbd "M-g Q") "Θ") ; THETA
(global-set-key (kbd "M-g I") "Ι") ; IOTA
(global-set-key (kbd "M-g K") "Κ") ; KAPPA
(global-set-key (kbd "M-g L") "Λ") ; LAMBDA
(global-set-key (kbd "M-g M") "Μ") ; MU
(global-set-key (kbd "M-g N") "Ν") ; NU
(global-set-key (kbd "M-g X") "Ξ") ; XI
(global-set-key (kbd "M-g O") "Ο") ; OMICRON
(global-set-key (kbd "M-g P") "Π") ; PI
(global-set-key (kbd "M-g R") "Ρ") ; RHO
(global-set-key (kbd "M-g S") "Σ") ; PSI
(global-set-key (kbd "M-g T") "Τ") ; TAU
(global-set-key (kbd "M-g U") "Υ") ; UPSILON
(global-set-key (kbd "M-g F") "Φ") ; PHI
(global-set-key (kbd "M-g J") "Φ") ; PHI
(global-set-key (kbd "M-g C") "Χ") ; XI
(global-set-key (kbd "M-g Y") "Ψ") ; PSI
(global-set-key (kbd "M-g W") "Ω") ; OMEGA
(global-set-key (kbd "M-g .") "∘")
(global-set-key (kbd "M-g *") "⊛")

#+END_SRC

** Thanks

For this configuration I've been inspired by:

- [fn:2]anler
- [fn:3]danielmai
- [fn:4]jwiegley
- [fn:5]abo-abo

* Footnotes

[fn:1] https://github.com/pashky/restclient.el
[fn:2] https://github.com/anler/.emacs.d
[fn:3] https://github.com/danielmai
[fn:4] https://github.com/jwiegley
[fn:5] https://github.com/abo-abo
